- en/guide/create-network/running-a-blockchain-node-with-dotnet-project.md
- ko/guide/create-network/running-a-blockchain-node-with-dotnet-project.md
> remove planet settings in `Running a Blockchain Node: .NET Project`

- en/guide/create-network/create-a-genesis-block.md
- en/guide/create-network/create-a-private-key.md
- en/index.md
- ko/guide/create-network/create-a-genesis-block.md
- ko/guide/create-network/create-a-private-key.md
- ko/index.md
> clean up documents

- en/index.md
> translate index

- en/index.md
- ko/index.md
> update index page

- en/network/create-network/create-a-genesis-block.md
- en/network/create-network/getting-started.md
- en/network/create-network/running-a-blockchain-node-with-dotnet-project.md
- en/network/issue-transaction/issue-transaction-with-chrono.md
- ko/network/create-network/create-a-genesis-block.md
- ko/network/create-network/getting-started.md
- ko/network/issue-transaction/issue-transaction-with-chrono.md
> clean up network parts

- .vitepress/config/en.mts
- .vitepress/config/ko.mts
- en/contributing/repositories.md
- en/index.md
- ko/contributing/repositories.md
- ko/index.md
> add contributing nav and edit hero actions

- .vitepress/config/en.mts
- .vitepress/config/ko.mts
- .vitepress/config/shared.mts
- en/contributing/getting-started.md
- ko/contributing/getting-started.md
- package-lock.json
- package.json
- yarn.lock
- Bump `yarn`, `vitepress` and `mermaid`.
- Use `withMermaid` function.
- Add `/contributing/getting-started` page.
> add /contributing/getting-started page with diagrams

- .vitepress/config/en.mts
- .vitepress/config/ko.mts
> fix navigation link

- .vitepress/config/en.mts
- .vitepress/config/ko.mts
- en/modding/system-guide/0-address-and-state.md
- en/modding/system-guide/agent.md
- en/modding/system-guide/avatar/0-avatar.md
- en/modding/system-guide/avatar/inventory.md
- en/modding/system-guide/avatar/quest-list.md
- en/modding/system-guide/avatar/world-information.md
- ko/modding/system-guide/0-address-and-state.md
- ko/modding/system-guide/agent.md
- ko/modding/system-guide/avatar/0-avatar.md
- ko/modding/system-guide/avatar/inventory.md
- ko/modding/system-guide/avatar/quest-list.md
- ko/modding/system-guide/avatar/world-information.md
> add Modding > System Guide

- en/modding/system-guide/adventure.md
- ko/modding/system-guide/adventure.md
> docs: add flowchart for skill selection

- .vitepress/config/en.mts
- .vitepress/config/ko.mts
- en/modding/system-guide/adventure.md
- en/modding/system-guide/arena.md
- ko/modding/system-guide/adventure.md
- ko/modding/system-guide/arena.md
> docs: write arena document

- .vitepress/config/en.mts
- .vitepress/config/ko.mts
This pull request removes `Forum Trunk` menu but the devforum articles aren't removed yet. It just removes `Forum Trunk` from the top menu.
> Remove Forum Trunk menu

- en/event/2024modathon.md
- ko/event/2024modathon.md
I want to guide readers who reading 2024Modathon event page, to tutorial pages (Avatar Information App, Daily Reward App).
> Rewrite the last section of 2024Modathon

- .vitepress/config/en.mts
> Fix Bloc → Block

- en/guide/general/get-state/get-state-with-mimir-graphql.md
- ko/guide/general/get-state/get-state-with-mimir-graphql.md
Fix for #91: Replaced links in documentation pointing to banana cake pop with Nitro
> Fix for Issue #91

- .vitepress/theme/en/CommunityDriven.vue
- .vitepress/theme/en/FullyOnChain.vue
- .vitepress/theme/en/ModdingFriendly.vue
- .vitepress/theme/en/WhatIsNineChronicles.vue
- .vitepress/theme/ko/CommunityDriven.vue
- .vitepress/theme/ko/FullyOnChain.vue
- .vitepress/theme/ko/ModdingFriendly.vue
- .vitepress/theme/ko/WhatIsNineChronicles.vue
> Fix responsiveness

- .vitepress/theme/en/WhatIsNineChronicles.vue
- .vitepress/theme/ko/WhatIsNineChronicles.vue
> Fix text overflow

- .vitepress/theme/en/ModdingFriendly.vue
- .vitepress/theme/ko/ModdingFriendly.vue
Solve https://github.com/planetarium/www.nine-chronicles.dev/issues/103
> Fix broken links

- .github/auto_assign.yml
It will become to assign reviewers automatically.
> Setup auto-assign

- .github/workflows/links.yml
- en/event/for-non-developer.md
- ko/event/for-non-developer.md
> Broken link checker

- .vitepress/theme/en/CommunityDriven.vue
> Fix #110: fix broken link
